// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSBZLT-EnhB-0d1JpywzAJADRx3kGdIRk',
    appId: '1:689141545944:web:f9d30d946bbafac30d50ad',
    messagingSenderId: '689141545944',
    projectId: 'cicada-c3ee0',
    authDomain: 'cicada-c3ee0.firebaseapp.com',
    storageBucket: 'cicada-c3ee0.appspot.com',
    measurementId: 'G-7TVKFXBXKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTz3VxSbThI9rWIxycx407pJMJR8zMr78',
    appId: '1:689141545944:android:3634d8b7130a6de90d50ad',
    messagingSenderId: '689141545944',
    projectId: 'cicada-c3ee0',
    storageBucket: 'cicada-c3ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5GHX9jf5dC7n_dETNAZ6DbtAZ2mDWio',
    appId: '1:689141545944:ios:7f5f60cfad54bb2e0d50ad',
    messagingSenderId: '689141545944',
    projectId: 'cicada-c3ee0',
    storageBucket: 'cicada-c3ee0.appspot.com',
    iosBundleId: 'com.example.cicada1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5GHX9jf5dC7n_dETNAZ6DbtAZ2mDWio',
    appId: '1:689141545944:ios:7f5f60cfad54bb2e0d50ad',
    messagingSenderId: '689141545944',
    projectId: 'cicada-c3ee0',
    storageBucket: 'cicada-c3ee0.appspot.com',
    iosBundleId: 'com.example.cicada1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSBZLT-EnhB-0d1JpywzAJADRx3kGdIRk',
    appId: '1:689141545944:web:1bab290e69c9a2fa0d50ad',
    messagingSenderId: '689141545944',
    projectId: 'cicada-c3ee0',
    authDomain: 'cicada-c3ee0.firebaseapp.com',
    storageBucket: 'cicada-c3ee0.appspot.com',
    measurementId: 'G-96H4YQFBSW',
  );
}
